logging:
  level:
    root: DEBUG
server:
  port: 9081
spring:
  datasource:
    url: jdbc:h2:file:${user.home}/aeprest1.db
    username: sa
    password: 
    driver-class-name: org.h2.Driver 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8